name: Build and Release App

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get app version
        uses: nyaa8/package-version@v1.0.3  

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependecies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag:  ${{ env.PACKAGE_VERSION }}
          name:  ${{ env.PACKAGE_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/bundle/*.zip"

