name: 'dhis2: tests'

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  dhis2-app:
    runs-on: ubuntu-latest
    # container: cypress/browsers:node14.7.0-chrome84
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install
      
      - name: Run the tests
        run: yarn test

      - name: Build
        run: yarn build

    env:
      CI: true
      REACT_APP_DHIS2_BASE_URL: 'https://debug.dhis2.org/ca-test-2.36'
