name: 'dhis2: tests'

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  cypress:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.7.0-chrome84
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          group: e2e-chrome-parallel
          browser: chrome
          start: 'yarn test'
          wait-on: 'http://localhost:3000'
          # wait for 200 secs for the server to respond
          wait-on-timeout: 200

    env:
      CI: true
      REACT_APP_DHIS2_BASE_URL: 'https://debug.dhis2.org/ca-test-2.36'
